### ISSUE TITLE
Run femtocleaner

### ISSUE THREAD

**Issue by SimonDanisch** [SimonDanisch/Clipper.jl#1]

**Comment by KristofferC** [comment]
Femtocleaner is in a bit of a sad mood at the moment (HTTP.jl is a bit buggy but there is a PR that is supposed to fix it).

If the Femtocleaner server is down you can use it locally as described in: https://github.com/JuliaComputing/FemtoCleaner.jl/blob/master/README.md#running-femtocleaner-locally

**Comment by SimonDanisch** [comment]
Thank you! :)

**Comment by KristofferC** [comment]
No problem, please say if you encounter any problems.
